import type {
  ChatMessage,
  OpportunityProtocolConfig,
  SurveyData,
} from "./types";

export const initialOpportunityProtocols: OpportunityProtocolConfig[] = [
  {
    id: "ghana-urban-informal",
    version: "opportunity-protocol-v0.1",
    contextName: "Ghana · urban informal repair",
    countryCode: "GH",
    region: "Greater Accra",
    locale: "en-GH",
    language: "English",
    currency: "GHS",
    educationTaxonomy: "Ghana SHS / TVET / informal apprenticeship",
    opportunityTypes: [
      "formal employment",
      "self-employment",
      "apprenticeship",
      "short training",
    ],
    automationCalibration:
      "Lower digital infrastructure and high in-person service demand reduce near-term substitution for repair and customer-facing work.",
    signalWeights: {
      skillFit: 36,
      localDemand: 18,
      wageFloor: 12,
      growth: 12,
      automationResilience: 12,
      trainingAccess: 10,
    },
    sources: [
      {
        id: "ilostat",
        label: "Employment and youth labor indicators",
        provider: "ILO",
        dataset: "ILOSTAT",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "wdi",
        label: "Macro and education context",
        provider: "World Bank",
        dataset: "World Development Indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "local-jobs",
        label: "Local vacancies and training places",
        provider: "Program partner",
        dataset: "CSV / API feed",
        year: "pilot sample",
        updateCycle: "monthly",
        status: "demo",
      },
      {
        id: "itu",
        label: "Connectivity constraint",
        provider: "ITU",
        dataset: "Digital Development indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
    ],
    econometricSignals: [
      {
        id: "youth_neet",
        category: "Youth employment",
        label: "Youth not in employment, education, or training",
        value: "admin upload",
        unit: "% of youth",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "High values push the matching layer toward reachable entry routes and training-linked work.",
        userVisible: true,
      },
      {
        id: "services_employment",
        category: "Sector structure",
        label: "Employment in services",
        value: "admin upload",
        unit: "% of employment",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "Service-sector weight helps rank repair, retail, customer support, and field-service routes.",
        userVisible: true,
      },
      {
        id: "mobile_broadband",
        category: "Digital constraint",
        label: "Mobile broadband access",
        value: "admin upload",
        unit: "subscriptions / 100 people",
        sourceId: "itu",
        year: "latest",
        interpretation:
          "Connectivity changes how realistic remote digital work is for the local context.",
        userVisible: true,
      },
    ],
    opportunities: [],
  },
  {
    id: "india-rural-agri",
    version: "opportunity-protocol-v0.1",
    contextName: "India · rural agricultural services",
    countryCode: "IN",
    region: "rural district pilot",
    locale: "en-IN",
    language: "English / local-language UI pack",
    currency: "INR",
    educationTaxonomy: "Class 10 / Class 12 / ITI / local training certificate",
    opportunityTypes: [
      "seasonal work",
      "self-employment",
      "field service",
      "training pathway",
    ],
    automationCalibration:
      "Mechanization risk differs by farm size, irrigation access, and local equipment availability.",
    signalWeights: {
      skillFit: 34,
      localDemand: 20,
      wageFloor: 10,
      growth: 14,
      automationResilience: 10,
      trainingAccess: 12,
    },
    sources: [
      {
        id: "ilostat",
        label: "Employment and sector status",
        provider: "ILO",
        dataset: "ILOSTAT",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "wdi",
        label: "Rural development indicators",
        provider: "World Bank",
        dataset: "World Development Indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "district-feed",
        label: "District job, training, and cooperative feed",
        provider: "State / NGO partner",
        dataset: "CSV / API feed",
        year: "pilot sample",
        updateCycle: "monthly",
        status: "demo",
      },
      {
        id: "itu",
        label: "Connectivity constraint",
        provider: "ITU",
        dataset: "Digital Development indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
    ],
    econometricSignals: [
      {
        id: "agri_employment",
        category: "Sector structure",
        label: "Employment in agriculture",
        value: "admin upload",
        unit: "% of employment",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "Agricultural employment share changes how heavily the engine ranks farm-service and equipment pathways.",
        userVisible: true,
      },
      {
        id: "youth_lfp",
        category: "Youth labor market",
        label: "Youth labor force participation",
        value: "admin upload",
        unit: "% of youth",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "Participation levels help distinguish job scarcity from skill-recognition gaps.",
        userVisible: true,
      },
      {
        id: "mobile_broadband",
        category: "Digital constraint",
        label: "Mobile broadband access",
        value: "admin upload",
        unit: "subscriptions / 100 people",
        sourceId: "itu",
        year: "latest",
        interpretation:
          "Connectivity determines whether remote data-collection and platform work are realistic.",
        userVisible: true,
      },
    ],
    opportunities: [],
  },
];

export const emptySurveyData: SurveyData = {
  age: null,
  sex: "",
  location: "",
  languages: [],
  work_authorization: "",
  availability: "",
  work_mode_preference: "",
  educational_level: "",
  target_outcome: "",
  target_roles: [],
  target_industries: [],
  time_horizon: "",
  priority_tradeoff: "",
  favorite_skill: "",
  current_role_title: "",
  current_industry: "",
  years_experience_total: "",
  years_experience_domain: "",
  skill_confidence: "",
  seniority_level: "",
  team_lead_experience: "",
  key_responsibilities: [],
  informal_experience: "",
  demonstrated_competencies: [],
  skills: [],
};

export const firstSurveyPrompt =
  "Hi, I am Milo. We can do this like a quick conversation. Tell me a little about yourself: what you are good at, what you enjoy doing, your sex, and the country you live in. I will pick up the details as we go.";

export const amaraDemoMessages: ChatMessage[] = [
  {
    role: "assistant",
    content: firstSurveyPrompt,
  },
  {
    role: "user",
    content:
      "I am 22 and live outside Accra in Ghana. I speak English fluently and Twi conversationally. I can work locally and remotely. I finished senior high school. I have 2 years of hands-on repair experience. My most fun skill is phone repair. I feel confident with phone repair 4 out of 5. I helped family and neighbors fix phones informally, and I can show that I diagnosed charging problems, replaced screens, talked to customers, kept records of parts and payments, and wrote basic HTML and JavaScript.",
  },
];

export const amaraSurveyData: SurveyData = {
  age: 22,
  sex: "female",
  location: "Accra, Ghana",
  languages: ["English fluent", "Twi conversational"],
  work_authorization: "Can work locally and remotely",
  availability: "",
  work_mode_preference: "local or remote",
  educational_level: "senior high school",
  target_outcome: "",
  target_roles: [],
  target_industries: [],
  time_horizon: "",
  priority_tradeoff: "",
  favorite_skill: "phone repair",
  current_role_title: "",
  current_industry: "repair services",
  years_experience_total: "2 years",
  years_experience_domain: "2 years in phone repair",
  skill_confidence: "phone repair 4/5",
  seniority_level: "",
  team_lead_experience: "",
  key_responsibilities: [
    "diagnosing charging problems",
    "replacing screens",
    "customer communication",
    "keeping records of parts and payments",
  ],
  informal_experience: "helped family and neighbors fix phones informally",
  demonstrated_competencies: [
    "diagnosing charging problems",
    "replacing screens",
    "customer communication",
    "keeping records of parts and payments",
    "basic HTML and JavaScript coding",
  ],
  skills: [
    "phone repair",
    "diagnosing charging problems",
    "replacing screens",
    "customer communication",
    "keeping records of parts and payments",
    "basic HTML and JavaScript coding",
  ],
};


